# Generated by Django 5.2 on 2025-04-17 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.CharField(max_length=1000, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания предложения"
                    ),
                ),
                (
                    "ad_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiver",
                        to="ads.ads",
                        verbose_name="Объявление получателя",
                    ),
                ),
                (
                    "ad_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ads.ads",
                        verbose_name="Объявление отправителя",
                    ),
                ),
            ],
        ),
    ]
