# Generated by Django 5.2 on 2025-04-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на картинку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объявления')),
            ],
        ),
    ]
